---
- name: create user account in ubuntu server
  hosts: fedora.lab.local
  vars_files:
    - secret.yml
  tasks:
    - name: creating the user 
      ansible.builtin.user:
        name: "{{ user }}"
