---
- name: Récupérer le nom d'hôte
  hosts: vagrant
  gather_facts: yes

  tasks:
    - name: Obtenir le nom d'hôte de la machine cible
      ansible.builtin.command:
        cmd: hostname
      register: hostname_result

    - name: Afficher le nom d'hôte
      ansible.builtin.debug:
        msg: "Le nom d'hôte de la machine {{ ansible_facts['default_ipv4']['address'] }} est {{ hostname_result.stdout }}"
      when: hostname_result is defined
