---
- name: Récupérer le nom d'hôte
  hosts: digitalocean
  gather_facts: no

  tasks:
    - name: Obtenir le nom d'hôte de la machine cible
      ansible.builtin.command:
        cmd: hostname
      register: hostname_result

    - name: Afficher le nom d'hôte
      ansible.builtin.debug:
        msg: "Le nom d'hôte de la machine 146.190.231.53 est {{ hostname_result.stdout }}"
      when: hostname_result is defined
