---
- name: Exemple de playbook avec handlers
  hosts: ubuntu
  gather_facts: no

  tasks:
    - name: Installe Nginx Server
      ansible.builtin.apt:
        name: nginx
        state: latest
      notify: restart nginx
    
    - name: Modifie un fichier de configuration
      ansible.builtin.lineinfile:
        path: /etc/nginx/nginx.conf
        line: "#daemon off;"
      notify: 
        - restart nginx
        - create temporary file
      

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
        
    - name: create temporary file
      ansible.builtin.copy:
        content: "create with handlers"
        dest: /tmp/handlers.txt

