---
- name: Install the required packages on the web server
  hosts: digitalocean
  tasks:
    - name: Install the httpd packages
      ansible.builtin.apt: // Fully Qualified Collection Name: FQCN
        name: nginx
        state: absent
