---
- name: Récupérer le nom d'hôte, afficher /etc/passwd et installer Apache
  hosts: digitalocean
  gather_facts: yes

  tasks:
    - name: Obtenir le nom d'hôte de la machine cible
      ansible.builtin.command:
        cmd: hostname
      register: hostname_result
      when: ansible_host == "146.190.231.53"

    - name: Afficher le nom d'hôte
      ansible.builtin.debug:
        msg: "Le nom d'hôte de la machine 146.190.231.53 est {{ hostname_result.stdout }}"
      when: hostname_result is defined

    - name: Afficher le contenu de /etc/passwd
      ansible.builtin.command:
        cmd: cat /etc/passwd
      register: etc_passwd
      when: ansible_host == "146.190.231.53"

    - name: Afficher le résultat de /etc/passwd
      ansible.builtin.debug:
        msg: "{{ etc_passwd.stdout }}"
      when: etc_passwd is defined

    - name: Installer Apache
      ansible.builtin.package:
        name: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
        state: present

