---
- name: Installer et démarrer Apache sur un serveur Ubuntu
  hosts: jenkins.lab.local
  tasks:
    - name: Mise à jour de la liste des paquets
      ansible.builtin.apt:
        update_cache: yes

    - name: remove Apache
      ansible.builtin.apt:
        name: apache2
        state: absent

