---
- name: Installer Apache sur un serveur Red Hat/CentOS
  hosts: webservers

  tasks:
    - name: Installer Apache (httpd)
      yum:
        name: httpd
        state: present
    - name: install vim editor in centos 9
      yum: 
        name: vim
        state: present

    - name: Démarrer le service Apache et s'assurer qu'il est activé au démarrage
      service:
        name: httpd
        state: started
        enabled: yes
