---
- name: Installer et démarrer Apache sur un serveur Ubuntu
  hosts: ubuntu-server
  tasks:
    - name: Mise à jour de la liste des paquets
      ansible.builtin.apt:
        update_cache: yes

    - name: Installation d'Apache
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: Démarrer le service Apache
      ansible.builtin.systemd:
        name: apache2
        state: started
        enabled: yes

