---
- name: Add marwa file
  hosts: 192.168.64.130
  become: yes
  vars:
    file: /home/alpine/marwa.txt
  tasks:
    - name: Update the package repository cache
      shell: touch {{ file }} && echo "date de naissance est 27/11/1989" >> {{ file }}
