---
- name: Add marwa file
  hosts: 192.168.64.130
  become: yes
  vars:
    file_path: /home/alpine/marwa.txt
    file_content: "date de naissance est 27/11/1989"

  tasks:
    - name: Ensure the file exists
      ansible.builtin.file:
        path: "{{ file_path }}"
        state: touch

    - name: Add content to the file
      ansible.builtin.lineinfile:
        path: "{{ file_path }}"
        line: "{{ file_content }}"
        create: yes
