---
- name: Add users with loop
  hosts: intranet.lab.local
  vars:
     list_users:
        - dev1
        - dev2
        - dev3
  tasks:
    - name: Add devuser
      ansible.builtin.user:
        name: "{{ item }}"
        state: absent
      loop: "{{ list_users }}"
        
