---
- name: Créer une instance EC2 t2.micro dans la région de Paris
  hosts: localhost
  gather_facts: false
  vars:
    region: "eu-west-3"   # Région de Paris
    instance_type: "t2.micro"  # Type d'instance
    image_id: "ami-0cb0b94275d5b4aec"  # AMI Ubuntu 20.04 pour la région Paris (vérifiez que l'AMI est toujours valide)
    key_name: "aws-ansible"   # Remplacez par votre clé SSH existante
    security_group: "sg-5363b028"  # Remplacez par votre groupe de sécurité existant
    subnet_id: "subnet-7b485e00"   # Remplacez par votre sous-réseau existant

  tasks:
    - name: Lancer une instance EC2
      amazon.aws.ec2_instance:
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ image_id }}"
        region: "{{ region }}"
        security_groups: 
          - "{{ security_group }}"
        subnet_id: "{{ subnet_id }}"
        wait: true
        tags:
          Name: "non-production"
        count: 1
      register: ec2

    - name: Afficher les informations sur l'instance créée
      debug:
        msg: "L'instance {{ ec2.instance_ids }} a été créée dans la région {{ region }} avec l'IP publique {{ ec2.instances[0].public_ip_address }}"
