---
- name: Créer une instance EC2 t2.micro
  amazon.aws.ec2_instance:
    key_name: "{{ key_name }}"
    instance_type: "{{ instance_type }}"
    image_id: "{{ image_id }}"
    region: "{{ region }}"
    security_groups: 
      - "{{ security_group }}"
    subnet_id: "{{ subnet_id }}"
    wait: true
    tags:
      Name: "{{ instance_name }}"
    count: 1
  register: ec2

- name: Afficher les informations de l'instance EC2 créée
  debug:
    msg: "L'instance {{ ec2.instance_ids }} a été créée avec l'IP publique {{ ec2.instances[0].public_ip_address }}"
